--- #YAML:1.0
name:                Win32-Uptime
version:             1.01
abstract:            Calculate uptime for Win32 systems
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Win32::API:                    0
    Win32::TieRegistry:            0.20
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Serguei Trouchelle <stro@railways.dp.ua>
